"""add base worth to movie

Revision ID: b528346bb568
Revises: 52c18388582d
Create Date: 2025-02-12 10:27:15.827607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b528346bb568'
down_revision: Union[str, None] = '52c18388582d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_on_account', sa.Column('base_worth', sa.Numeric(precision=100, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_on_account', 'base_worth')
    # ### end Alembic commands ###
