"""update user

Revision ID: 6284e4917856
Revises: e464c65a3fe7
Create Date: 2025-01-21 19:27:25.451909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6284e4917856'
down_revision: Union[str, None] = 'e464c65a3fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registration', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('user', sa.Column('last_visit', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.drop_column('user', 'currencies')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('currencies', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'last_visit')
    op.drop_column('user', 'registration')
    # ### end Alembic commands ###
