"""add separate table earnings

Revision ID: 2ff84a6d3d89
Revises: 6284e4917856
Create Date: 2025-01-21 22:41:48.002676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff84a6d3d89'
down_revision: Union[str, None] = '6284e4917856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('earning_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['user.chat_id'], name=op.f('fk_earnings_chat_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('earning_id', name=op.f('pk_earnings'))
    )
    op.add_column('movie_on_account', sa.Column('categories_id', sa.Integer(), nullable=True))
    op.add_column('movie_on_account', sa.Column('earnings_id', sa.Integer(), nullable=True))
    op.drop_column('movie_on_account', 'earnings_type')
    op.drop_column('movie_on_account', 'categories_name')
    op.drop_column('user', 'type_of_earnings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('type_of_earnings', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('movie_on_account', sa.Column('categories_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('movie_on_account', sa.Column('earnings_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('movie_on_account', 'earnings_id')
    op.drop_column('movie_on_account', 'categories_id')
    op.drop_table('earnings')
    # ### end Alembic commands ###
