"""add currencies amount

Revision ID: ae7c0a77a946
Revises: 5d75467e0378
Create Date: 2025-06-22 23:23:54.321017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7c0a77a946'
down_revision: Union[str, None] = '5d75467e0378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_currency',
    sa.Column('table_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('cash_account_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=100, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cash_account_id'], ['cash_account.table_id'], name=op.f('fk_category_currency_cash_account_id_cash_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.table_id'], name=op.f('fk_category_currency_category_id_category'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_id'], ['user.chat_id'], name=op.f('fk_category_currency_chat_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('table_id', name=op.f('pk_category_currency')),
    sa.UniqueConstraint('category_id', 'cash_account_id', 'currency', name='_category_currency_uc')
    )
    op.create_table('earnings_currency',
    sa.Column('table_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('earnings_id', sa.Integer(), nullable=False),
    sa.Column('cash_account_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=100, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cash_account_id'], ['cash_account.table_id'], name=op.f('fk_earnings_currency_cash_account_id_cash_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_id'], ['user.chat_id'], name=op.f('fk_earnings_currency_chat_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['earnings_id'], ['earnings.table_id'], name=op.f('fk_earnings_currency_earnings_id_earnings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('table_id', name=op.f('pk_earnings_currency')),
    sa.UniqueConstraint('earnings_id', 'cash_account_id', 'currency', name='_earnings_currency_uc')
    )
    op.drop_column('balance', 'balance')
    op.drop_column('cash_account', 'balance')
    op.drop_column('category', 'balance')
    op.drop_column('earnings', 'balance')
    op.drop_column('movie_on_account', 'base_worth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_on_account', sa.Column('base_worth', sa.NUMERIC(precision=100, scale=2), autoincrement=False, nullable=False))
    op.add_column('earnings', sa.Column('balance', sa.NUMERIC(precision=100, scale=2), autoincrement=False, nullable=False))
    op.add_column('category', sa.Column('balance', sa.NUMERIC(precision=100, scale=2), autoincrement=False, nullable=False))
    op.add_column('cash_account', sa.Column('balance', sa.NUMERIC(precision=100, scale=2), autoincrement=False, nullable=False))
    op.add_column('balance', sa.Column('balance', sa.NUMERIC(precision=100, scale=2), autoincrement=False, nullable=False))
    op.drop_table('earnings_currency')
    op.drop_table('category_currency')
    # ### end Alembic commands ###
