"""add balances history

Revision ID: 4d4a478476ae
Revises: 7686f2f67809
Create Date: 2025-07-01 22:35:40.266597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4a478476ae'
down_revision: Union[str, None] = '7686f2f67809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance', sa.Column('balances_history', sa.ARRAY(sa.Numeric(precision=19, scale=4)), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balance', 'balances_history')
    # ### end Alembic commands ###
