"""DataBase creation

Revision ID: 679eb28dfeba
Revises: 
Create Date: 2024-12-04 16:58:06.920898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '679eb28dfeba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currencies', sa.String(), nullable=False),
    sa.Column('categories', sa.String(), nullable=True),
    sa.Column('type_of_earnings', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_balance', sa.Float(), nullable=False),
    sa.Column('balances_history', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name=op.f('fk_balance_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_balance'))
    )
    op.create_table('cash_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('cash', 'card', name='cashaccounttype'), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_cash_account_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_account'))
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.Enum('black', 'white', 'auto', name='theme'), nullable=False),
    sa.Column('language', sa.Enum('english', 'russian', name='language'), nullable=False),
    sa.Column('notifications', sa.Boolean(), nullable=False),
    sa.Column('main_currency', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name=op.f('fk_settings_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings'))
    )
    op.create_table('movie_on_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('type', sa.Enum('earning', 'outlay', name='movietype'), nullable=False),
    sa.Column('worth', sa.Numeric(), nullable=False),
    sa.Column('cash_account', sa.Integer(), nullable=False),
    sa.Column('categories_name', sa.String(), nullable=False),
    sa.Column('earnings_type', sa.String(), nullable=False),
    sa.Column('time', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['cash_account'], ['cash_account.id'], name=op.f('fk_movie_on_account_cash_account_cash_account'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name=op.f('fk_movie_on_account_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movie_on_account'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_on_account')
    op.drop_table('settings')
    op.drop_table('cash_account')
    op.drop_table('balance')
    op.drop_table('user')
    # ### end Alembic commands ###
