"""add Category with new constrait

Revision ID: e464c65a3fe7
Revises: 4bd38631b4c0
Create Date: 2025-01-03 18:12:31.656305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e464c65a3fe7'
down_revision: Union[str, None] = '4bd38631b4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('month_limit', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['user.chat_id'], name=op.f('fk_category_chat_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_category'))
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
