"""new category new constraits

Revision ID: d0e8492d39b3
Revises: 0b674650d5f2
Create Date: 2025-01-03 15:39:50.316269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e8492d39b3'
down_revision: Union[str, None] = '0b674650d5f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('category',
    sa.Column('movie_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('month_limit', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['user.chat_id'], name=op.f('fk_category_chat_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', name=op.f('pk_category'))
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
