"""add optional descrition

Revision ID: 5d75467e0378
Revises: de7841632f53
Create Date: 2025-05-14 13:16:20.335714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d75467e0378'
down_revision: Union[str, None] = 'de7841632f53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cash_account', 'description',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('earnings', 'description',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('earnings', 'description',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('cash_account', 'description',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###
