"""change name total balance to balace in Balance table

Revision ID: 8618fc4f7d38
Revises: 29b53a6f73e1
Create Date: 2025-02-21 11:27:58.274578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8618fc4f7d38'
down_revision: Union[str, None] = '29b53a6f73e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance', sa.Column('balance', sa.Numeric(precision=100, scale=2), nullable=False))
    op.drop_column('balance', 'total_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance', sa.Column('total_balance', sa.NUMERIC(precision=100, scale=2), autoincrement=False, nullable=False))
    op.drop_column('balance', 'balance')
    # ### end Alembic commands ###
