"""drop Category

Revision ID: 0b674650d5f2
Revises: 37224f72d3bb
Create Date: 2025-01-03 15:38:48.819352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b674650d5f2'
down_revision: Union[str, None] = '37224f72d3bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table('category')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('month_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['user.chat_id'], name='fk_category_chat_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', name='pk_category')
    )
    # ### end Alembic commands ###
