"""change name Category id

Revision ID: 5728f61381af
Revises: d0e8492d39b3
Create Date: 2025-01-03 15:46:49.783220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5728f61381af'
down_revision: Union[str, None] = 'd0e8492d39b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('category', 'movie_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('movie_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('category', 'category_id')
    # ### end Alembic commands ###
